[
  "Petróleo e Gás - Refino",
  "Mineração",
  "Bancos",
  "Bebidas",
  "Motores e Compressores",
  "Energia - Distribuição",
  "Holding",
  "Bolsa de Valores",
  "Serviços Hospitalares",
  "Telecomunicações",
  "Locação - Veículos",
  "Seguros",
  "Papel e Celulose",
  "Varejo - Farmacêutico",
  "Siderurgia",
  "Logística e Ferroviário",
  "Alimentos - Carnes e Derivados",
  "Petróleo e Gás - Distribuição",
  "Saneamento",
  "Energia - Geração",
  "Aéreo",
  "Petróleo e Gás - E&P",
  "Medicamentos",
  "Exploração de Rodovias",
  "Varejo - Geral",
  "Varejo - Alimentício",
  "Químicos",
  "Gás",
  "Produtos de Uso Pessoal",
  "Vestuário - Geral",
  "Software",
  "Energia - Transmissão",
  "Shoppings",
  "Produção de Aeronaves",
  "Alimentos - Variados",
  "Meios de Pagamento",
  "Açúcar e Álcool",
  "Academias",
  "Serviços Diversos",
  "Produtos Diversos",
  "Vestuário - Calçados",
  "Medicina Diagnóstica",
  "Logística e Portuário",
  "Agronegócio",
  "Construção",
  "Produtos para Construção Civil",
  "Eletrodomésticos",
  "Artigos de Luxo",
  "Educação",
  "Automotivo",
  "Locação - Máquinas e Equip.",
  "Logística e Hidroviário",
  "Alumínio",
  "Pet shop",
  "Ambiental",
  "Logística e Rodoviário",
  "Hardware",
  "Armas e Munições",
  "Máquinas e Equipamentos",
  "Fertilizantes",
  "Mercado Financeiro",
  "Segurança da Informação",
  "Restaurantes",
  "Programas e Serviços",
  "Madeira",
  "Documentos de Segurança",
  "Turismo",
  "Exploração de Imóveis",
  "Estacionamento",
  "Têxtil",
  "Financeira",
  "Produtos de Limpeza",
  "Móveis",
  "Entretenimento",
  "Bicicletas",
  "Utensílios Domésticos",
  "Consultoria",
  "Brinquedos e Jogos",
  "Hotelaria"
].each { |name| Api::V1::Sector.find_or_create_by(name: name) }
