[
 "Petróleo e Gás - Refino",
 "Mineração",
 "Bancos",
 "Bebidas",
 "Motores e Compressores",
 "Energia - Distribuição",
 "Holding",
 "Telecomunicações",
 "Bolsa de Valores",
 "Seguros",
 "Papel e Celulose",
 "Locação - Veículos",
 "Serviços Hospitalares",
 "Varejo - Farmacêutico",
 "Siderurgia",
 "Logística e Ferroviário",
 "Alimentos - Carnes e Derivados",
].each { |name| Api::V1::Segment.find_or_create_by(name: name) }
