default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: investment_api_development
  host: localhost
  username: postgres
  password: postgres
  port: 5432
test:
  <<: *default
  database: investment_api_test
  host: localhost
  username: postgres
  password: postgres
  port: 5432
production:
  <<: *default
  database: investment_api_production
  username: investment_api
  password: <%= ENV["INVESTMENT_API_DATABASE_PASSWORD"] %>
