name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12.7
        env:
          POSTGRES_DB: investment_api_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: "postgres"
        ports: ["5432:5432"]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2.1
        bundler-cache: true

    - name: Setup test database
      env:
        RAILS_ENV: test
        PGHOST: localhost
        PGUSER: postgres
      run: |
        bin/rails db:drop
        bin/rails db:create
        bin/rails db:migrate

    - name: Run tests
      run: |
        bundle exec rspec
